on: [push, pull_request]
name: CI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ocaml-version:
          - 4.08.1
          - 4.09.1
          - 4.10.1
          - 4.11.0
          - 4.12.0
        depopts:
          -
          - zarith
        test:
          -
          - --with-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add bitwuzla.dev . --no-action

      - run: opam depext bitwuzla --yes ${{ matrix.test }}

      - run: opam install bitwuzla --deps-only ${{ matrix.test }}

      - if: matrix.depopts != ''
        run: opam install ${{ matrix.depopts }}

      - run: rm vendor/cadical/src/makefile

      - run: opam exec -- dune build @install

      - if: matrix.test != ''
        run: opam exec -- dune build @runtest
